# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Global Configuration

#  title	String	---	The title of the website
#   description	String	---	A description of you or the blog. Alias for "about"
#   about	String	---	About you or about the blog
#   about_img	Filepath	---	Image to display in the "About" section
#   navbar_img	Filepath	---	Image to display in the top navbar
#   favicon_img	Filepath	---	Image to display in browser tab
#   paginate	Number	---	How many posts to show on the home page
#   exclude_powered_by	Boolean	false	Remove the "powered by..." credit in the footer
#   google_analytics	String	---	Google Analytics tracking ID
#   disqus	String	---	Disqus short name

# Post Configuration

#   description	String	---	A description of the current post
#   author	String or Array	---	The author name(s) of the post
#   mathjax	Boolean	false	Enable MathJax on this page
#   katex	Boolean	false	Enable KaTex on this page
#   comments	Boolean	true	Enable the Disqus comment system
#   toc	Boolean	false	Enable the TOC


title: The BS Blog
email: brian.sheridan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am very driven and enjoy solving business problems with technology. I have over 20 years of experience in all areas of technology positions. I've worked as a Helpdesk Support, Server Administrator, Network Administrator, Programmer, Architect, Engineering Manager, and Director of Technology.

  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
exclude_powered_by: false
markdown: kramdown
paginate: 5


# Build settings
#theme: minima
remote_theme: slee981/jekyll-theme-cadre
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
